### ISSUE TITLE
User는 나의 피드 화면에서 사진 타입/타입라인 타입의 피드를 확인할 수 있다.

### ISSUE THREAD

**Issue by chiyoon** [boostcampwm-2021/android04-God-Fisherman#47]
- [ ] 나의 피드 화면에서 나의 피드를 확인할 수 있다.
- [ ] 피드 타입과 세부 정보는 피드 화면 epic#피드 story#1 task#1.1 ~ 1.2.5 와 동일하다.
- [ ] 사용자는 세로 스크롤을 통해 새로운 피드 정보를 계속해서 볼 수 있다.

**Comment by potatoyum** [comment]
기능 삭제
